--require("obsidian").setup({
--    workspaces = {
--        {
--            name = "pessoal",
--            path = "~/vaults/pessoal",
--        },
--        {
--            name = "trabalho",
--            path = "~/vaults/trabalho",
--        },
--        {
--            name = "estudos",
--            path = "~/vaults/estudos",
--        },
--    },
--})
